sudo: true
dist: xenial
language: go
services:
- docker
before_install:
- IMAGE=keptnexamples/notification-service
- VERSION="$(cat version | tr -d '[:space:]')"
- echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
- REPO_URL="$(git remote get-url --all origin)"
- ./writeManifest.sh
- cat MANIFEST
- cp MANIFEST docker-image/
jobs:
  include:
  - stage: master
    if: branch = master AND NOT type = pull_request
    script:
    - echo $TRAVIS_BUILD_STAGE_NAME
    - cd docker-image
    - docker build . -t "${IMAGE}:${VERSION}"
    - docker push "${IMAGE}:${VERSION}"
